spring:
  application:
    name: ticket-app
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  # Cache configuration
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  
  # Security configuration
  security:
    # Set to false to disable authentication (useful for development)
    enabled: ${SECURITY_ENABLED:true}
    oauth2:
      resourceserver:
        jwt:
          # Configure this to point to your organization's OIDC provider
          # Example: https://your-oidc-provider.com/.well-known/jwks.json
          jwk-set-uri: ${OIDC_JWK_SET_URI:https://your-oidc-provider.com/.well-known/jwks.json}
          # Optional: Configure issuer validation
          issuer-uri: ${OIDC_ISSUER_URI:https://your-oidc-provider.com}

# Server configuration
server:
  port: 8080

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
  endpoint:
    health:
      show-details: always
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

# Application configuration
app:
  security:
    # Set to true to enable mock JWT tokens for testing
    mock-jwt: true

# Logging configuration
logging:
  level:
    com.ticketapp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
